const POPULAR_CITIES = [
    // Kerala Cities (Priority)
    { name: "Thiruvananthapuram", country: "IN" },
    { name: "Kochi", country: "IN" },
    { name: "Kozhikode", country: "IN" },
    { name: "Thrissur", country: "IN" },
    { name: "Kollam", country: "IN" },
    { name: "Palakkad", country: "IN" },
    { name: "Alappuzha", country: "IN" },
    { name: "Malappuram", country: "IN" },
    { name: "Kannur", country: "IN" },
    { name: "Kasaragod", country: "IN" },
    { name: "Kottayam", country: "IN" },
    { name: "Pathanamthitta", country: "IN" },
    { name: "Idukki", country: "IN" },
    { name: "Wayanad", country: "IN" },
    { name: "Ernakulam", country: "IN" },
    { name: "Thalassery", country: "IN" },
    { name: "Perinthalmanna", country: "IN" },
    { name: "Chavakkad", country: "IN" },
    { name: "Koyilandy", country: "IN" },
    { name: "Nedumangad", country: "IN" },
    { name: "Kannur Cantonment", country: "IN" },
    { name: "Kanhangad", country: "IN" },
    { name: "Payyanur", country: "IN" },
    { name: "Kalpetta", country: "IN" },
    { name: "Mattanur", country: "IN" },
    { name: "Punalur", country: "IN" },
    { name: "Nilambur", country: "IN" },
    { name: "Cherthala", country: "IN" },
    { name: "Sulthan Bathery", country: "IN" },
    { name: "Maradu", country: "IN" },
    { name: "Kottakkal", country: "IN" },
    { name: "Thodupuzha", country: "IN" },
    { name: "Kayamkulam", country: "IN" },
    { name: "Manjeri", country: "IN" },
    { name: "Vadakara", country: "IN" },
    { name: "Neyyattinkara", country: "IN" },
    { name: "Paravur", country: "IN" },
    { name: "Thrippunithura", country: "IN" },
    { name: "Ponnani", country: "IN" },
    { name: "Kodungallur", country: "IN" },
    { name: "Ottappalam", country: "IN" },
    { name: "Tirur", country: "IN" },
    { name: "Changanassery", country: "IN" },
    { name: "Muvattupuzha", country: "IN" },
    { name: "Attingal", country: "IN" },
    { name: "Varkala", country: "IN" },
    { name: "Kothamangalam", country: "IN" },
    { name: "Cherpulassery", country: "IN" },
    { name: "Perumbavoor", country: "IN" },
    { name: "Kalamassery", country: "IN" },
    { name: "Shoranur", country: "IN" },
    { name: "Kunnamkulam", country: "IN" },
    { name: "Pandalam", country: "IN" },
    { name: "Pathanapuram", country: "IN" },
    { name: "Mavelikkara", country: "IN" },
    { name: "Adoor", country: "IN" },
    { name: "Feroke", country: "IN" },
    { name: "Chengannur", country: "IN" },
    { name: "Guruvayur", country: "IN" },
    { name: "Pattambi", country: "IN" },
    { name: "Angamaly", country: "IN" },
    { name: "Irinjalakuda", country: "IN" },
    { name: "Payyoli", country: "IN" },
    
    // Other Major Indian Cities
    { name: "Mumbai", country: "IN" },
    { name: "Delhi", country: "IN" },
    { name: "Bangalore", country: "IN" },
    { name: "Hyderabad", country: "IN" },
    { name: "Ahmedabad", country: "IN" },
    { name: "Chennai", country: "IN" },
    { name: "Kolkata", country: "IN" },
    { name: "Pune", country: "IN" },
    { name: "Jaipur", country: "IN" },
    { name: "Surat", country: "IN" },
    { name: "Lucknow", country: "IN" },
    { name: "Kanpur", country: "IN" },
    { name: "Nagpur", country: "IN" },
    { name: "Indore", country: "IN" },
    { name: "Thane", country: "IN" },
    { name: "Bhopal", country: "IN" },
    { name: "Visakhapatnam", country: "IN" },
    { name: "Pimpri-Chinchwad", country: "IN" },
    { name: "Patna", country: "IN" },
    { name: "Vadodara", country: "IN" },
    { name: "Ghaziabad", country: "IN" },
    { name: "Ludhiana", country: "IN" },
    { name: "Agra", country: "IN" },
    { name: "Nashik", country: "IN" },
    { name: "Faridabad", country: "IN" },
    { name: "Meerut", country: "IN" },
    { name: "Rajkot", country: "IN" },
    { name: "Kalyan-Dombivali", country: "IN" },
    { name: "Vasai-Virar", country: "IN" },
    { name: "Varanasi", country: "IN" },
    { name: "Srinagar", country: "IN" },
    { name: "Aurangabad", country: "IN" },
    { name: "Dhanbad", country: "IN" },
    { name: "Amritsar", country: "IN" },
    { name: "Navi Mumbai", country: "IN" },
    { name: "Allahabad", country: "IN" },
    { name: "Ranchi", country: "IN" },
    { name: "Howrah", country: "IN" },
    { name: "Coimbatore", country: "IN" },
    { name: "Jabalpur", country: "IN" },
    { name: "Gwalior", country: "IN" },
    { name: "Vijayawada", country: "IN" },
    { name: "Jodhpur", country: "IN" },
    { name: "Madurai", country: "IN" },
    { name: "Raipur", country: "IN" },
    { name: "Kota", country: "IN" },
    { name: "Chandigarh", country: "IN" },
    { name: "Guwahati", country: "IN" },
    { name: "Solapur", country: "IN" },
    { name: "Hubli-Dharwad", country: "IN" },
    { name: "Tiruchirappalli", country: "IN" },
    { name: "Bareilly", country: "IN" },
    { name: "Mysore", country: "IN" },
    { name: "Tiruppur", country: "IN" },
    { name: "Gurgaon", country: "IN" },
    { name: "Aligarh", country: "IN" },
    { name: "Jalandhar", country: "IN" },
    { name: "Bhubaneswar", country: "IN" },
    { name: "Salem", country: "IN" },
    { name: "Mira-Bhayandar", country: "IN" },
    { name: "Warangal", country: "IN" },
    { name: "Thiruvananthapuram", country: "IN" },
    { name: "Guntur", country: "IN" },
    { name: "Bhiwandi", country: "IN" },
    { name: "Saharanpur", country: "IN" },
    { name: "Gorakhpur", country: "IN" },
    { name: "Bikaner", country: "IN" },
    { name: "Amravati", country: "IN" },
    { name: "Noida", country: "IN" },
    { name: "Jamshedpur", country: "IN" },
    { name: "Bhilai", country: "IN" },
    { name: "Cuttack", country: "IN" },
    { name: "Firozabad", country: "IN" },
    { name: "Kochi", country: "IN" },
    { name: "Nellore", country: "IN" },
    { name: "Bhavnagar", country: "IN" },
    { name: "Dehradun", country: "IN" },
    { name: "Durgapur", country: "IN" },
    { name: "Asansol", country: "IN" },
    { name: "Rourkela", country: "IN" },
    { name: "Nanded", country: "IN" },
    { name: "Kolhapur", country: "IN" },
    { name: "Ajmer", country: "IN" },
    { name: "Akola", country: "IN" },
    { name: "Gulbarga", country: "IN" },
    { name: "Jamnagar", country: "IN" },
    { name: "Ujjain", country: "IN" },
    { name: "Loni", country: "IN" },
    { name: "Siliguri", country: "IN" },
    { name: "Jhansi", country: "IN" },
    { name: "Ulhasnagar", country: "IN" },
    { name: "Jammu", country: "IN" },
    { name: "Mangalore", country: "IN" },
    { name: "Erode", country: "IN" },
    { name: "Belgaum", country: "IN" },
    { name: "Ambattur", country: "IN" },
    { name: "Tirunelveli", country: "IN" },
    { name: "Malegaon", country: "IN" },
    { name: "Gaya", country: "IN" },
    { name: "Jalgaon", country: "IN" },
    { name: "Udaipur", country: "IN" },
    { name: "Maheshtala", country: "IN" },
    
    // Tamil Nadu Cities
    { name: "Vellore", country: "IN" },
    { name: "Thanjavur", country: "IN" },
    { name: "Dindigul", country: "IN" },
    { name: "Karur", country: "IN" },
    { name: "Kumbakonam", country: "IN" },
    { name: "Tirupati", country: "IN" },
    { name: "Avadi", country: "IN" },
    { name: "Tambaram", country: "IN" },
    { name: "Hosur", country: "IN" },
    { name: "Pallavaram", country: "IN" },
    
    // Karnataka Cities
    { name: "Davangere", country: "IN" },
    { name: "Bellary", country: "IN" },
    { name: "Bijapur", country: "IN" },
    { name: "Shimoga", country: "IN" },
    { name: "Tumkur", country: "IN" },
    { name: "Raichur", country: "IN" },
    { name: "Bidar", country: "IN" },
    { name: "Hospet", country: "IN" },
    { name: "Hassan", country: "IN" },
    { name: "Gadag-Betigeri", country: "IN" },
    { name: "Udupi", country: "IN" },
    { name: "Mandya", country: "IN" },
    
    // Andhra Pradesh & Telangana
    { name: "Rajahmundry", country: "IN" },
    { name: "Nizamabad", country: "IN" },
    { name: "Karimnagar", country: "IN" },
    { name: "Khammam", country: "IN" },
    { name: "Eluru", country: "IN" },
    { name: "Anantapur", country: "IN" },
    { name: "Kadapa", country: "IN" },
    { name: "Kurnool", country: "IN" },
    { name: "Ongole", country: "IN" },
    { name: "Machilipatnam", country: "IN" },
    
    // Maharashtra Cities
    { name: "Ahmednagar", country: "IN" },
    { name: "Chandrapur", country: "IN" },
    { name: "Parbhani", country: "IN" },
    { name: "Jalna", country: "IN" },
    { name: "Bhusawal", country: "IN" },
    { name: "Nanded-Waghala", country: "IN" },
    { name: "Latur", country: "IN" },
    { name: "Dhule", country: "IN" },
    { name: "Ahmednagar", country: "IN" },
    { name: "Ichalkaranji", country: "IN" },
    
    // Gujarat Cities
    { name: "Anand", country: "IN" },
    { name: "Morbi", country: "IN" },
    { name: "Mahesana", country: "IN" },
    { name: "Bharuch", country: "IN" },
    { name: "Vapi", country: "IN" },
    { name: "Navsari", country: "IN" },
    { name: "Veraval", country: "IN" },
    { name: "Porbandar", country: "IN" },
    { name: "Godhra", country: "IN" },
    { name: "Botad", country: "IN" },
    
    // Rajasthan Cities
    { name: "Alwar", country: "IN" },
    { name: "Bharatpur", country: "IN" },
    { name: "Sikar", country: "IN" },
    { name: "Pali", country: "IN" },
    { name: "Sri Ganganagar", country: "IN" },
    { name: "Tonk", country: "IN" },
    { name: "Kishangarh", country: "IN" },
    { name: "Beawar", country: "IN" },
    { name: "Hanumangarh", country: "IN" },
    
    // Madhya Pradesh Cities
    { name: "Sagar", country: "IN" },
    { name: "Dewas", country: "IN" },
    { name: "Satna", country: "IN" },
    { name: "Ratlam", country: "IN" },
    { name: "Rewa", country: "IN" },
    { name: "Murwara", country: "IN" },
    { name: "Singrauli", country: "IN" },
    { name: "Burhanpur", country: "IN" },
    { name: "Khandwa", country: "IN" },
    
    // Uttar Pradesh Cities
    { name: "Moradabad", country: "IN" },
    { name: "Mysore", country: "IN" },
    { name: "Rampur", country: "IN" },
    { name: "Shahjahanpur", country: "IN" },
    { name: "Farrukhabad", country: "IN" },
    { name: "Muzaffarnagar", country: "IN" },
    { name: "Mathura", country: "IN" },
    { name: "Budaun", country: "IN" },
    { name: "Sambhal", country: "IN" },
    { name: "Amroha", country: "IN" },
    { name: "Hardoi", country: "IN" },
    { name: "Fatehpur", country: "IN" },
    { name: "Raebareli", country: "IN" },
    { name: "Orai", country: "IN" },
    { name: "Sitapur", country: "IN" },
    { name: "Bahraich", country: "IN" },
    { name: "Modinagar", country: "IN" },
    { name: "Unnao", country: "IN" },
    { name: "Jaunpur", country: "IN" },
    { name: "Lakhimpur", country: "IN" },
    { name: "Hathras", country: "IN" },
    { name: "Banda", country: "IN" },
    { name: "Pilibhit", country: "IN" },
    { name: "Barabanki", country: "IN" },
    { name: "Khurja", country: "IN" },
    { name: "Gonda", country: "IN" },
    { name: "Mainpuri", country: "IN" },
    { name: "Lalitpur", country: "IN" },
    { name: "Etah", country: "IN" },
    { name: "Deoria", country: "IN" },
    { name: "Ujhani", country: "IN" },
    { name: "Ghazipur", country: "IN" },
    { name: "Sultanpur", country: "IN" },
    { name: "Azamgarh", country: "IN" },
    { name: "Bijnor", country: "IN" },
    { name: "Sahaswan", country: "IN" },
    { name: "Basti", country: "IN" },
    { name: "Chandausi", country: "IN" },
    { name: "Akbarpur", country: "IN" },
    { name: "Ballia", country: "IN" },
    { name: "Tanda", country: "IN" },
    { name: "Greater Noida", country: "IN" },
    { name: "Shikohabad", country: "IN" },
    { name: "Shamli", country: "IN" },
    { name: "Awagarh", country: "IN" },
    { name: "Kasganj", country: "IN" },
    
    // Punjab Cities
    { name: "Patiala", country: "IN" },
    { name: "Bathinda", country: "IN" },
    { name: "Pathankot", country: "IN" },
    { name: "Hoshiarpur", country: "IN" },
    { name: "Batala", country: "IN" },
    { name: "Moga", country: "IN" },
    { name: "Malerkotla", country: "IN" },
    { name: "Khanna", country: "IN" },
    { name: "Mohali", country: "IN" },
    { name: "Barnala", country: "IN" },
    { name: "Firozpur", country: "IN" },
    { name: "Kapurthala", country: "IN" },
    { name: "Zirakpur", country: "IN" },
    { name: "Kot Kapura", country: "IN" },
    { name: "Faridkot", country: "IN" },
    { name: "Muktsar", country: "IN" },
    { name: "Rajpura", country: "IN" },
    { name: "Sangrur", country: "IN" },
    { name: "Fazilka", country: "IN" },
    { name: "Gurdaspur", country: "IN" },
    { name: "Kharar", country: "IN" },
    { name: "Gobindgarh", country: "IN" },
    { name: "Mansa", country: "IN" },
    { name: "Malout", country: "IN" },
    { name: "Nabha", country: "IN" },
    { name: "Tarn Taran", country: "IN" },
    { name: "Jagraon", country: "IN" },
    { name: "Sunam", country: "IN" },
    { name: "Dhuri", country: "IN" },
    { name: "Firozpur Cantonment", country: "IN" },
    { name: "Sirhind Fatehgarh Sahib", country: "IN" },
    { name: "Rupnagar", country: "IN" },
    { name: "Jalandhar Cantonment", country: "IN" },
    { name: "Samana", country: "IN" },
    { name: "Nawanshahr", country: "IN" },
    { name: "Rampura Phul", country: "IN" },
    { name: "Nangal", country: "IN" },
    { name: "Nakodar", country: "IN" },
    { name: "Zira", country: "IN" },
    { name: "Patti", country: "IN" },
    { name: "Raikot", country: "IN" },
    { name: "Longowal", country: "IN" },
    { name: "Urmar Tanda", country: "IN" },
    { name: "Morinda", country: "IN" },
    { name: "Phillaur", country: "IN" },
    { name: "Pattran", country: "IN" },
    { name: "Qadian", country: "IN" },
    { name: "Sujanpur", country: "IN" },
    { name: "Mukerian", country: "IN" },
    { name: "Talwara", country: "IN" },
    
    // Haryana Cities
    { name: "Panipat", country: "IN" },
    { name: "Ambala", country: "IN" },
    { name: "Yamunanagar", country: "IN" },
    { name: "Rohtak", country: "IN" },
    { name: "Hisar", country: "IN" },
    { name: "Karnal", country: "IN" },
    { name: "Sonipat", country: "IN" },
    { name: "Panchkula", country: "IN" },
    { name: "Bhiwani", country: "IN" },
    { name: "Sirsa", country: "IN" },
    { name: "Bahadurgarh", country: "IN" },
    { name: "Jind", country: "IN" },
    { name: "Thanesar", country: "IN" },
    { name: "Kaithal", country: "IN" },
    { name: "Rewari", country: "IN" },
    { name: "Palwal", country: "IN" },
    
    // Himachal Pradesh
    { name: "Shimla", country: "IN" },
    { name: "Mandi", country: "IN" },
    { name: "Solan", country: "IN" },
    { name: "Nahan", country: "IN" },
    { name: "Sundarnagar", country: "IN" },
    { name: "Palampur", country: "IN" },
    
    // Uttarakhand
    { name: "Haridwar", country: "IN" },
    { name: "Roorkee", country: "IN" },
    { name: "Haldwani-cum-Kathgodam", country: "IN" },
    { name: "Rudrapur", country: "IN" },
    { name: "Kashipur", country: "IN" },
    { name: "Rishikesh", country: "IN" },
    
    // Bihar
    { name: "Gaya", country: "IN" },
    { name: "Bhagalpur", country: "IN" },
    { name: "Muzaffarpur", country: "IN" },
    { name: "Darbhanga", country: "IN" },
    { name: "Arrah", country: "IN" },
    { name: "Begusarai", country: "IN" },
    { name: "Katihar", country: "IN" },
    { name: "Munger", country: "IN" },
    { name: "Chhapra", country: "IN" },
    { name: "Purnia", country: "IN" },
    { name: "Saharsa", country: "IN" },
    { name: "Sasaram", country: "IN" },
    { name: "Hajipur", country: "IN" },
    { name: "Dehri-on-Sone", country: "IN" },
    { name: "Bettiah", country: "IN" },
    { name: "Motihari", country: "IN" },
    { name: "Bagaha", country: "IN" },
    { name: "Siwan", country: "IN" },
    { name: "Kishanganj", country: "IN" },
    { name: "Jamalpur", country: "IN" },
    { name: "Buxar", country: "IN" },
    { name: "Jehanabad", country: "IN" },
    { name: "Aurangabad", country: "IN" },
    
    // Jharkhand
    { name: "Bokaro Steel City", country: "IN" },
    { name: "Deoghar", country: "IN" },
    { name: "Phusro", country: "IN" },
    { name: "Adityapur", country: "IN" },
    { name: "Hazaribag", country: "IN" },
    { name: "Giridih", country: "IN" },
    { name: "Ramgarh", country: "IN" },
    { name: "Medininagar", country: "IN" },
    { name: "Chirkunda", country: "IN" },
    
    // Odisha
    { name: "Rourkela", country: "IN" },
    { name: "Berhampur", country: "IN" },
    { name: "Sambalpur", country: "IN" },
    { name: "Puri", country: "IN" },
    { name: "Balasore", country: "IN" },
    { name: "Bhadrak", country: "IN" },
    { name: "Baripada", country: "IN" },
    
    // West Bengal
    { name: "Durgapur", country: "IN" },
    { name: "Asansol", country: "IN" },
    { name: "Siliguri", country: "IN" },
    { name: "Bardhaman", country: "IN" },
    { name: "Baharampur", country: "IN" },
    { name: "Habra", country: "IN" },
    { name: "Kharagpur", country: "IN" },
    { name: "Shantipur", country: "IN" },
    { name: "Dankuni", country: "IN" },
    { name: "Dhulian", country: "IN" },
    { name: "Raniganj", country: "IN" },
    { name: "Haldia", country: "IN" },
    { name: "Raiganj", country: "IN" },
    { name: "Krishnanagar", country: "IN" },
    { name: "Nabadwip", country: "IN" },
    { name: "Medinipur", country: "IN" },
    { name: "Jalpaiguri", country: "IN" },
    { name: "Balurghat", country: "IN" },
    { name: "Basirhat", country: "IN" },
    { name: "Bankura", country: "IN" },
    { name: "Chakdaha", country: "IN" },
    { name: "Darjeeling", country: "IN" },
    { name: "Alipurduar", country: "IN" },
    { name: "Purulia", country: "IN" },
    { name: "Jangipur", country: "IN" },
    { name: "Bangaon", country: "IN" },
    
    // Assam
    { name: "Silchar", country: "IN" },
    { name: "Dibrugarh", country: "IN" },
    { name: "Jorhat", country: "IN" },
    { name: "Bongaigaon City", country: "IN" },
    { name: "Tinsukia", country: "IN" },
    { name: "Tezpur", country: "IN" },
    { name: "Kamrup Metropolitan", country: "IN" },
    { name: "Nagaon", country: "IN" },
    { name: "Karimganj", country: "IN" },
    { name: "Sivasagar", country: "IN" },
    
    // Chhattisgarh
    { name: "Bilaspur", country: "IN" },
    { name: "Korba", country: "IN" },
    { name: "Durg", country: "IN" },
    { name: "Rajnandgaon", country: "IN" },
    { name: "Jagdalpur", country: "IN" },
    { name: "Raigarh", country: "IN" },
    { name: "Ambikapur", country: "IN" },
    
    // Goa
    { name: "Panaji", country: "IN" },
    { name: "Margao", country: "IN" },
    { name: "Vasco da Gama", country: "IN" },
    { name: "Mapusa", country: "IN" },
    { name: "Ponda", country: "IN" },
    
    // Northeast States
    { name: "Imphal", country: "IN" },
    { name: "Aizawl", country: "IN" },
    { name: "Agartala", country: "IN" },
    { name: "Shillong", country: "IN" },
    { name: "Itanagar", country: "IN" },
    { name: "Kohima", country: "IN" },
    { name: "Dimapur", country: "IN" },
    { name: "Gangtok", country: "IN" },
    
    // International Cities - Asia
    { name: "Tokyo", country: "JP" },
    { name: "Yokohama", country: "JP" },
    { name: "Osaka", country: "JP" },
    { name: "Nagoya", country: "JP" },
    { name: "Sapporo", country: "JP" },
    { name: "Fukuoka", country: "JP" },
    { name: "Kobe", country: "JP" },
    { name: "Kyoto", country: "JP" },
    { name: "Kawasaki", country: "JP" },
    { name: "Saitama", country: "JP" },
    { name: "Hiroshima", country: "JP" },
    { name: "Sendai", country: "JP" },
    { name: "Kitakyushu", country: "JP" },
    { name: "Chiba", country: "JP" },
    { name: "Sakai", country: "JP" },
    { name: "Niigata", country: "JP" },
    { name: "Hamamatsu", country: "JP" },
    { name: "Kumamoto", country: "JP" },
    { name: "Sagamihara", country: "JP" },
    { name: "Okayama", country: "JP" },
    
    { name: "Shanghai", country: "CN" },
    { name: "Beijing", country: "CN" },
    { name: "Guangzhou", country: "CN" },
    { name: "Shenzhen", country: "CN" },
    { name: "Chengdu", country: "CN" },
    { name: "Chongqing", country: "CN" },
    { name: "Tianjin", country: "CN" },
    { name: "Wuhan", country: "CN" },
    { name: "Dongguan", country: "CN" },
    { name: "Hangzhou", country: "CN" },
    { name: "Foshan", country: "CN" },
    { name: "Shenyang", country: "CN" },
    { name: "Nanjing", country: "CN" },
    { name: "Xi'an", country: "CN" },
    { name: "Harbin", country: "CN" },
    { name: "Qingdao", country: "CN" },
    { name: "Changsha", country: "CN" },
    { name: "Dalian", country: "CN" },
    { name: "Zhengzhou", country: "CN" },
    { name: "Shantou", country: "CN" },
    { name: "Jinan", country: "CN" },
    { name: "Changchun", country: "CN" },
    { name: "Kunming", country: "CN" },
    { name: "Ürümqi", country: "CN" },
    { name: "Xiamen", country: "CN" },
    { name: "Taiyuan", country: "CN" },
    { name: "Hefei", country: "CN" },
    { name: "Shijiazhuang", country: "CN" },
    { name: "Nanning", country: "CN" },
    { name: "Guiyang", country: "CN" },
    
    { name: "Seoul", country: "KR" },
    { name: "Busan", country: "KR" },
    { name: "Incheon", country: "KR" },
    { name: "Daegu", country: "KR" },
    { name: "Daejeon", country: "KR" },
    { name: "Gwangju", country: "KR" },
    { name: "Suwon", country: "KR" },
    { name: "Ulsan", country: "KR" },
    { name: "Changwon", country: "KR" },
    { name: "Goyang", country: "KR" },
    
    { name: "Bangkok", country: "TH" },
    { name: "Nonthaburi", country: "TH" },
    { name: "Nakhon Ratchasima", country: "TH" },
    { name: "Chiang Mai", country: "TH" },
    { name: "Hat Yai", country: "TH" },
    { name: "Udon Thani", country: "TH" },
    { name: "Pak Kret", country: "TH" },
    { name: "Khon Kaen", country: "TH" },
    { name: "Pattaya", country: "TH" },
    { name: "Nakhon Si Thammarat", country: "TH" },
    
    { name: "Singapore", country: "SG" },
    
    { name: "Hong Kong", country: "HK" },
    
    { name: "Kuala Lumpur", country: "MY" },
    { name: "George Town", country: "MY" },
    { name: "Ipoh", country: "MY" },
    { name: "Johor Bahru", country: "MY" },
    { name: "Shah Alam", country: "MY" },
    { name: "Petaling Jaya", country: "MY" },
    { name: "Kota Kinabalu", country: "MY" },
    { name: "Seremban", country: "MY" },
    { name: "Klang", country: "MY" },
    { name: "Malacca City", country: "MY" },
    
    { name: "Jakarta", country: "ID" },
    { name: "Surabaya", country: "ID" },
    { name: "Bandung", country: "ID" },
    { name: "Bekasi", country: "ID" },
    { name: "Medan", country: "ID" },
    { name: "Tangerang", country: "ID" },
    { name: "Depok", country: "ID" },
    { name: "Semarang", country: "ID" },
    { name: "Palembang", country: "ID" },
    { name: "Makassar", country: "ID" },
    { name: "South Tangerang", country: "ID" },
    { name: "Batam", country: "ID" },
    { name: "Bogor", country: "ID" },
    { name: "Pekanbaru", country: "ID" },
    { name: "Bandar Lampung", country: "ID" },
    
    { name: "Manila", country: "PH" },
    { name: "Quezon City", country: "PH" },
    { name: "Davao City", country: "PH" },
    { name: "Caloocan", country: "PH" },
    { name: "Cebu City", country: "PH" },
    { name: "Zamboanga City", country: "PH" },
    { name: "Taguig", country: "PH" },
    { name: "Pasig", country: "PH" },
    { name: "Antipolo", country: "PH" },
    { name: "Cagayan de Oro", country: "PH" },
    
    { name: "Hanoi", country: "VN" },
    { name: "Ho Chi Minh City", country: "VN" },
    { name: "Da Nang", country: "VN" },
    { name: "Can Tho", country: "VN" },
    { name: "Haiphong", country: "VN" },
    { name: "Bien Hoa", country: "VN" },
    { name: "Hue", country: "VN" },
    { name: "Nha Trang", country: "VN" },
    { name: "Buon Ma Thuot", country: "VN" },
    { name: "Vung Tau", country: "VN" },
    
    { name: "Yangon", country: "MM" },
    { name: "Mandalay", country: "MM" },
    { name: "Naypyidaw", country: "MM" },
    
    { name: "Dhaka", country: "BD" },
    { name: "Chittagong", country: "BD" },
    { name: "Khulna", country: "BD" },
    { name: "Rajshahi", country: "BD" },
    { name: "Sylhet", country: "BD" },
    { name: "Bogra", country: "BD" },
    { name: "Barisal", country: "BD" },
    { name: "Comilla", country: "BD" },
    { name: "Mymensingh", country: "BD" },
    { name: "Rangpur", country: "BD" },
    
    { name: "Karachi", country: "PK" },
    { name: "Lahore", country: "PK" },
    { name: "Faisalabad", country: "PK" },
    { name: "Rawalpindi", country: "PK" },
    { name: "Multan", country: "PK" },
    { name: "Hyderabad", country: "PK" },
    { name: "Gujranwala", country: "PK" },
    { name: "Peshawar", country: "PK" },
    { name: "Quetta", country: "PK" },
    { name: "Islamabad", country: "PK" },
    
    { name: "Colombo", country: "LK" },
    { name: "Dehiwala-Mount Lavinia", country: "LK" },
    { name: "Moratuwa", country: "LK" },
    { name: "Jaffna", country: "LK" },
    { name: "Negombo", country: "LK" },
    { name: "Kandy", country: "LK" },
    { name: "Sri Jayewardenepura Kotte", country: "LK" },
    { name: "Trincomalee", country: "LK" },
    { name: "Galle", country: "LK" },
    { name: "Batticaloa", country: "LK" },
    
    { name: "Kathmandu", country: "NP" },
    { name: "Pokhara", country: "NP" },
    { name: "Lalitpur", country: "NP" },
    { name: "Bharatpur", country: "NP" },
    { name: "Biratnagar", country: "NP" },
    
    { name: "Kabul", country: "AF" },
    { name: "Kandahar", country: "AF" },
    { name: "Herat", country: "AF" },
    { name: "Mazar-i-Sharif", country: "AF" },
    
    { name: "Tehran", country: "IR" },
    { name: "Mashhad", country: "IR" },
    { name: "Isfahan", country: "IR" },
    { name: "Karaj", country: "IR" },
    { name: "Tabriz", country: "IR" },
    { name: "Shiraz", country: "IR" },
    { name: "Qom", country: "IR" },
    { name: "Ahvaz", country: "IR" },
    { name: "Kermanshah", country: "IR" },
    { name: "Urmia", country: "IR" },
    
    { name: "Baghdad", country: "IQ" },
    { name: "Basra", country: "IQ" },
    { name: "Mosul", country: "IQ" },
    { name: "Erbil", country: "IQ" },
    { name: "Najaf", country: "IQ" },
    { name: "Sulaymaniyah", country: "IQ" },
    { name: "Karbala", country: "IQ" },
    { name: "Kirkuk", country: "IQ" },
    
    { name: "Riyadh", country: "SA" },
    { name: "Jeddah", country: "SA" },
    { name: "Mecca", country: "SA" },
    { name: "Medina", country: "SA" },
    { name: "Dammam", country: "SA" },
    { name: "Khobar", country: "SA" },
    { name: "Tabuk", country: "SA" },
    { name: "Ta'if", country: "SA" },
    { name: "Buraidah", country: "SA" },
    { name: "Khamis Mushait", country: "SA" },
    
    { name: "Dubai", country: "AE" },
    { name: "Abu Dhabi", country: "AE" },
    { name: "Sharjah", country: "AE" },
    { name: "Al Ain", country: "AE" },
    { name: "Ajman", country: "AE" },
    { name: "Ras Al Khaimah", country: "AE" },
    { name: "Fujairah", country: "AE" },
    { name: "Umm Al Quwain", country: "AE" },
    
    { name: "Kuwait City", country: "KW" },
    { name: "Al Ahmadi", country: "KW" },
    { name: "Hawalli", country: "KW" },
    { name: "As Salimiyah", country: "KW" },
    { name: "Sabah As Salim", country: "KW" },
    
    { name: "Doha", country: "QA" },
    { name: "Al Rayyan", country: "QA" },
    { name: "Umm Salal", country: "QA" },
    { name: "Al Wakrah", country: "QA" },
    
    { name: "Manama", country: "BH" },
    { name: "Riffa", country: "BH" },
    { name: "Muharraq", country: "BH" },
    { name: "Hamad Town", country: "BH" },
    
    { name: "Muscat", country: "OM" },
    { name: "Seeb", country: "OM" },
    { name: "Salalah", country: "OM" },
    { name: "Bawshar", country: "OM" },
    { name: "Sohar", country: "OM" },
    
    { name: "Sanaa", country: "YE" },
    { name: "Aden", country: "YE" },
    { name: "Taiz", country: "YE" },
    { name: "Al Hudaydah", country: "YE" },
    
    { name: "Amman", country: "JO" },
    { name: "Zarqa", country: "JO" },
    { name: "Irbid", country: "JO" },
    { name: "Russeifa", country: "JO" },
    
    { name: "Beirut", country: "LB" },
    { name: "Tripoli", country: "LB" },
    { name: "Sidon", country: "LB" },
    { name: "Tyre", country: "LB" },
    
    { name: "Damascus", country: "SY" },
    { name: "Aleppo", country: "SY" },
    { name: "Homs", country: "SY" },
    { name: "Latakia", country: "SY" },
    
    { name: "Jerusalem", country: "IL" },
    { name: "Tel Aviv", country: "IL" },
    { name: "Haifa", country: "IL" },
    { name: "Rishon LeZion", country: "IL" },
    { name: "Petah Tikva", country: "IL" },
    { name: "Ashdod", country: "IL" },
    { name: "Netanya", country: "IL" },
    { name: "Be'er Sheva", country: "IL" },
    { name: "Holon", country: "IL" },
    { name: "Ramat Gan", country: "IL" },
    
    { name: "Istanbul", country: "TR" },
    { name: "Ankara", country: "TR" },
    { name: "Izmir", country: "TR" },
    { name: "Bursa", country: "TR" },
    { name: "Adana", country: "TR" },
    { name: "Gaziantep", country: "TR" },
    { name: "Konya", country: "TR" },
    { name: "Antalya", country: "TR" },
    { name: "Kayseri", country: "TR" },
    { name: "Mersin", country: "TR" },
    
    // Europe
    { name: "London", country: "GB" },
    { name: "Birmingham", country: "GB" },
    { name: "Leeds", country: "GB" },
    { name: "Glasgow", country: "GB" },
    { name: "Sheffield", country: "GB" },
    { name: "Manchester", country: "GB" },
    { name: "Edinburgh", country: "GB" },
    { name: "Liverpool", country: "GB" },
    { name: "Bristol", country: "GB" },
    { name: "Cardiff", country: "GB" },
    { name: "Leicester", country: "GB" },
    { name: "Coventry", country: "GB" },
    { name: "Bradford", country: "GB" },
    { name: "Nottingham", country: "GB" },
    { name: "Kingston upon Hull", country: "GB" },
    { name: "Newcastle upon Tyne", country: "GB" },
    { name: "Belfast", country: "GB" },
    { name: "Stoke-on-Trent", country: "GB" },
    { name: "Southampton", country: "GB" },
    { name: "Derby", country: "GB" },
    
    { name: "Paris", country: "FR" },
    { name: "Marseille", country: "FR" },
    { name: "Lyon", country: "FR" },
    { name: "Toulouse", country: "FR" },
    { name: "Nice", country: "FR" },
    { name: "Nantes", country: "FR" },
    { name: "Strasbourg", country: "FR" },
    { name: "Montpellier", country: "FR" },
    { name: "Bordeaux", country: "FR" },
    { name: "Lille", country: "FR" },
    { name: "Rennes", country: "FR" },
    { name: "Reims", country: "FR" },
    { name: "Le Havre", country: "FR" },
    { name: "Saint-Étienne", country: "FR" },
    { name: "Toulon", country: "FR" },
    { name: "Grenoble", country: "FR" },
    { name: "Dijon", country: "FR" },
    { name: "Angers", country: "FR" },
    { name: "Nîmes", country: "FR" },
    { name: "Villeurbanne", country: "FR" },
    
    { name: "Berlin", country: "DE" },
    { name: "Hamburg", country: "DE" },
    { name: "Munich", country: "DE" },
    { name: "Cologne", country: "DE" },
    { name: "Frankfurt", country: "DE" },
    { name: "Stuttgart", country: "DE" },
    { name: "Düsseldorf", country: "DE" },
    { name: "Dortmund", country: "DE" },
    { name: "Essen", country: "DE" },
    { name: "Leipzig", country: "DE" },
    { name: "Bremen", country: "DE" },
    { name: "Dresden", country: "DE" },
    { name: "Hanover", country: "DE" },
    { name: "Nuremberg", country: "DE" },
    { name: "Duisburg", country: "DE" },
    { name: "Bochum", country: "DE" },
    { name: "Wuppertal", country: "DE" },
    { name: "Bielefeld", country: "DE" },
    { name: "Bonn", country: "DE" },
    { name: "Münster", country: "DE" },
    
    { name: "Madrid", country: "ES" },
    { name: "Barcelona", country: "ES" },
    { name: "Valencia", country: "ES" },
    { name: "Seville", country: "ES" },
    { name: "Zaragoza", country: "ES" },
    { name: "Málaga", country: "ES" },
    { name: "Murcia", country: "ES" },
    { name: "Palma", country: "ES" },
    { name: "Las Palmas", country: "ES" },
    { name: "Bilbao", country: "ES" },
    { name: "Alicante", country: "ES" },
    { name: "Córdoba", country: "ES" },
    { name: "Valladolid", country: "ES" },
    { name: "Vigo", country: "ES" },
    { name: "Gijón", country: "ES" },
    { name: "L'Hospitalet de Llobregat", country: "ES" },
    { name: "A Coruña", country: "ES" },
    { name: "Granada", country: "ES" },
    { name: "Vitoria-Gasteiz", country: "ES" },
    { name: "Elche", country: "ES" },
    
    { name: "Rome", country: "IT" },
    { name: "Milan", country: "IT" },
    { name: "Naples", country: "IT" },
    { name: "Turin", country: "IT" },
    { name: "Palermo", country: "IT" },
    { name: "Genoa", country: "IT" },
    { name: "Bologna", country: "IT" },
    { name: "Florence", country: "IT" },
    { name: "Bari", country: "IT" },
    { name: "Catania", country: "IT" },
    { name: "Venice", country: "IT" },
    { name: "Verona", country: "IT" },
    { name: "Messina", country: "IT" },
    { name: "Padua", country: "IT" },
    { name: "Trieste", country: "IT" },
    { name: "Taranto", country: "IT" },
    { name: "Brescia", country: "IT" },
    { name: "Parma", country: "IT" },
    { name: "Prato", country: "IT" },
    { name: "Modena", country: "IT" },
    
    { name: "Amsterdam", country: "NL" },
    { name: "Rotterdam", country: "NL" },
    { name: "The Hague", country: "NL" },
    { name: "Utrecht", country: "NL" },
    { name: "Eindhoven", country: "NL" },
    { name: "Tilburg", country: "NL" },
    { name: "Groningen", country: "NL" },
    { name: "Almere", country: "NL" },
    { name: "Breda", country: "NL" },
    { name: "Nijmegen", country: "NL" },
    
    { name: "Brussels", country: "BE" },
    { name: "Antwerp", country: "BE" },
    { name: "Ghent", country: "BE" },
    { name: "Charleroi", country: "BE" },
    { name: "Liège", country: "BE" },
    { name: "Bruges", country: "BE" },
    { name: "Namur", country: "BE" },
    { name: "Leuven", country: "BE" },
    
    { name: "Vienna", country: "AT" },
    { name: "Graz", country: "AT" },
    { name: "Linz", country: "AT" },
    { name: "Salzburg", country: "AT" },
    { name: "Innsbruck", country: "AT" },
    
    { name: "Zurich", country: "CH" },
    { name: "Geneva", country: "CH" },
    { name: "Basel", country: "CH" },
    { name: "Bern", country: "CH" },
    { name: "Lausanne", country: "CH" },
    { name: "Winterthur", country: "CH" },
    { name: "Lucerne", country: "CH" },
    { name: "St. Gallen", country: "CH" },
    
    { name: "Stockholm", country: "SE" },
    { name: "Gothenburg", country: "SE" },
    { name: "Malmö", country: "SE" },
    { name: "Uppsala", country: "SE" },
    { name: "Västerås", country: "SE" },
    { name: "Örebro", country: "SE" },
    { name: "Linköping", country: "SE" },
    { name: "Helsingborg", country: "SE" },
    
    { name: "Copenhagen", country: "DK" },
    { name: "Aarhus", country: "DK" },
    { name: "Odense", country: "DK" },
    { name: "Aalborg", country: "DK" },
    { name: "Frederiksberg", country: "DK" },
    
    { name: "Oslo", country: "NO" },
    { name: "Bergen", country: "NO" },
    { name: "Trondheim", country: "NO" },
    { name: "Stavanger", country: "NO" },
    { name: "Drammen", country: "NO" },
    
    { name: "Helsinki", country: "FI" },
    { name: "Espoo", country: "FI" },
    { name: "Tampere", country: "FI" },
    { name: "Vantaa", country: "FI" },
    { name: "Oulu", country: "FI" },
    
    { name: "Moscow", country: "RU" },
    { name: "Saint Petersburg", country: "RU" },
    { name: "Novosibirsk", country: "RU" },
    { name: "Yekaterinburg", country: "RU" },
    { name: "Nizhny Novgorod", country: "RU" },
    { name: "Kazan", country: "RU" },
    { name: "Chelyabinsk", country: "RU" },
    { name: "Omsk", country: "RU" },
    { name: "Samara", country: "RU" },
    { name: "Rostov-on-Don", country: "RU" },
    { name: "Ufa", country: "RU" },
    { name: "Krasnoyarsk", country: "RU" },
    { name: "Voronezh", country: "RU" },
    { name: "Perm", country: "RU" },
    { name: "Volgograd", country: "RU" },
    
    { name: "Kyiv", country: "UA" },
    { name: "Kharkiv", country: "UA" },
    { name: "Odesa", country: "UA" },
    { name: "Dnipro", country: "UA" },
    { name: "Donetsk", country: "UA" },
    { name: "Zaporizhzhia", country: "UA" },
    { name: "Lviv", country: "UA" },
    
    { name: "Warsaw", country: "PL" },
    { name: "Kraków", country: "PL" },
    { name: "Łódź", country: "PL" },
    { name: "Wrocław", country: "PL" },
    { name: "Poznań", country: "PL" },
    { name: "Gdańsk", country: "PL" },
    { name: "Szczecin", country: "PL" },
    { name: "Bydgoszcz", country: "PL" },
    { name: "Lublin", country: "PL" },
    { name: "Katowice", country: "PL" },
    
    { name: "Bucharest", country: "RO" },
    { name: "Cluj-Napoca", country: "RO" },
    { name: "Timișoara", country: "RO" },
    { name: "Iași", country: "RO" },
    { name: "Constanța", country: "RO" },
    { name: "Craiova", country: "RO" },
    { name: "Brașov", country: "RO" },
    { name: "Galați", country: "RO" },
    
    { name: "Prague", country: "CZ" },
    { name: "Brno", country: "CZ" },
    { name: "Ostrava", country: "CZ" },
    { name: "Plzeň", country: "CZ" },
    { name: "Liberec", country: "CZ" },
    
    { name: "Budapest", country: "HU" },
    { name: "Debrecen", country: "HU" },
    { name: "Szeged", country: "HU" },
    { name: "Miskolc", country: "HU" },
    { name: "Pécs", country: "HU" },
    
    { name: "Athens", country: "GR" },
    { name: "Thessaloniki", country: "GR" },
    { name: "Patras", country: "GR" },
    { name: "Piraeus", country: "GR" },
    { name: "Larissa", country: "GR" },
    
    { name: "Lisbon", country: "PT" },
    { name: "Porto", country: "PT" },
    { name: "Vila Nova de Gaia", country: "PT" },
    { name: "Amadora", country: "PT" },
    { name: "Braga", country: "PT" },
    { name: "Coimbra", country: "PT" },
    { name: "Setúbal", country: "PT" },
    { name: "Funchal", country: "PT" },
    
    { name: "Dublin", country: "IE" },
    { name: "Cork", country: "IE" },
    { name: "Limerick", country: "IE" },
    { name: "Galway", country: "IE" },
    { name: "Waterford", country: "IE" },
    
    // North America
    { name: "New York", country: "US" },
    { name: "Los Angeles", country: "US" },
    { name: "Chicago", country: "US" },
    { name: "Houston", country: "US" },
    { name: "Phoenix", country: "US" },
    { name: "Philadelphia", country: "US" },
    { name: "San Antonio", country: "US" },
    { name: "San Diego", country: "US" },
    { name: "Dallas", country: "US" },
    { name: "San Jose", country: "US" },
    { name: "Austin", country: "US" },
    { name: "Jacksonville", country: "US" },
    { name: "Fort Worth", country: "US" },
    { name: "Columbus", country: "US" },
    { name: "Charlotte", country: "US" },
    { name: "San Francisco", country: "US" },
    { name: "Indianapolis", country: "US" },
    { name: "Seattle", country: "US" },
    { name: "Denver", country: "US" },
    { name: "Washington", country: "US" },
    { name: "Boston", country: "US" },
    { name: "El Paso", country: "US" },
    { name: "Nashville", country: "US" },
    { name: "Detroit", country: "US" },
    { name: "Oklahoma City", country: "US" },
    { name: "Portland", country: "US" },
    { name: "Las Vegas", country: "US" },
    { name: "Memphis", country: "US" },
    { name: "Louisville", country: "US" },
    { name: "Baltimore", country: "US" },
    { name: "Milwaukee", country: "US" },
    { name: "Albuquerque", country: "US" },
    { name: "Tucson", country: "US" },
    { name: "Fresno", country: "US" },
    { name: "Mesa", country: "US" },
    { name: "Sacramento", country: "US" },
    { name: "Atlanta", country: "US" },
    { name: "Kansas City", country: "US" },
    { name: "Colorado Springs", country: "US" },
    { name: "Miami", country: "US" },
    { name: "Raleigh", country: "US" },
    { name: "Omaha", country: "US" },
    { name: "Long Beach", country: "US" },
    { name: "Virginia Beach", country: "US" },
    { name: "Oakland", country: "US" },
    { name: "Minneapolis", country: "US" },
    { name: "Tulsa", country: "US" },
    { name: "Tampa", country: "US" },
    { name: "Arlington", country: "US" },
    { name: "New Orleans", country: "US" },
    
    { name: "Toronto", country: "CA" },
    { name: "Montreal", country: "CA" },
    { name: "Vancouver", country: "CA" },
    { name: "Calgary", country: "CA" },
    { name: "Edmonton", country: "CA" },
    { name: "Ottawa", country: "CA" },
    { name: "Winnipeg", country: "CA" },
    { name: "Quebec City", country: "CA" },
    { name: "Hamilton", country: "CA" },
    { name: "Kitchener", country: "CA" },
    { name: "London", country: "CA" },
    { name: "Victoria", country: "CA" },
    { name: "Halifax", country: "CA" },
    { name: "Oshawa", country: "CA" },
    { name: "Windsor", country: "CA" },
    
    { name: "Mexico City", country: "MX" },
    { name: "Guadalajara", country: "MX" },
    { name: "Monterrey", country: "MX" },
    { name: "Puebla", country: "MX" },
    { name: "Tijuana", country: "MX" },
    { name: "León", country: "MX" },
    { name: "Juárez", country: "MX" },
    { name: "Zapopan", country: "MX" },
    { name: "Mérida", country: "MX" },
    { name: "San Luis Potosí", country: "MX" },
    { name: "Aguascalientes", country: "MX" },
    { name: "Hermosillo", country: "MX" },
    { name: "Saltillo", country: "MX" },
    { name: "Mexicali", country: "MX" },
    { name: "Culiacán", country: "MX" },
    { name: "Cancún", country: "MX" },
    { name: "Acapulco", country: "MX" },
    { name: "Veracruz", country: "MX" },
    
    // South America
    { name: "São Paulo", country: "BR" },
    { name: "Rio de Janeiro", country: "BR" },
    { name: "Brasília", country: "BR" },
    { name: "Salvador", country: "BR" },
    { name: "Fortaleza", country: "BR" },
    { name: "Belo Horizonte", country: "BR" },
    { name: "Manaus", country: "BR" },
    { name: "Curitiba", country: "BR" },
    { name: "Recife", country: "BR" },
    { name: "Porto Alegre", country: "BR" },
    { name: "Belém", country: "BR" },
    { name: "Goiânia", country: "BR" },
    { name: "Guarulhos", country: "BR" },
    { name: "Campinas", country: "BR" },
    { name: "São Luís", country: "BR" },
    { name: "São Gonçalo", country: "BR" },
    { name: "Maceió", country: "BR" },
    { name: "Duque de Caxias", country: "BR" },
    { name: "Natal", country: "BR" },
    { name: "Teresina", country: "BR" },
    
    { name: "Buenos Aires", country: "AR" },
    { name: "Córdoba", country: "AR" },
    { name: "Rosario", country: "AR" },
    { name: "Mendoza", country: "AR" },
    { name: "La Plata", country: "AR" },
    { name: "San Miguel de Tucumán", country: "AR" },
    { name: "Mar del Plata", country: "AR" },
    { name: "Salta", country: "AR" },
    { name: "Santa Fe", country: "AR" },
    { name: "San Juan", country: "AR" },
    
    { name: "Lima", country: "PE" },
    { name: "Arequipa", country: "PE" },
    { name: "Trujillo", country: "PE" },
    { name: "Chiclayo", country: "PE" },
    { name: "Piura", country: "PE" },
    { name: "Iquitos", country: "PE" },
    { name: "Cusco", country: "PE" },
    { name: "Huancayo", country: "PE" },
    
    { name: "Bogotá", country: "CO" },
    { name: "Medellín", country: "CO" },
    { name: "Cali", country: "CO" },
    { name: "Barranquilla", country: "CO" },
    { name: "Cartagena", country: "CO" },
    { name: "Cúcuta", country: "CO" },
    { name: "Bucaramanga", country: "CO" },
    { name: "Pereira", country: "CO" },
    { name: "Santa Marta", country: "CO" },
    { name: "Ibagué", country: "CO" },
    
    { name: "Santiago", country: "CL" },
    { name: "Valparaíso", country: "CL" },
    { name: "Concepción", country: "CL" },
    { name: "La Serena", country: "CL" },
    { name: "Antofagasta", country: "CL" },
    { name: "Temuco", country: "CL" },
    { name: "Rancagua", country: "CL" },
    { name: "Talca", country: "CL" },
    
    { name: "Caracas", country: "VE" },
    { name: "Maracaibo", country: "VE" },
    { name: "Valencia", country: "VE" },
    { name: "Barquisimeto", country: "VE" },
    { name: "Maracay", country: "VE" },
    
    { name: "Quito", country: "EC" },
    { name: "Guayaquil", country: "EC" },
    { name: "Cuenca", country: "EC" },
    { name: "Santo Domingo", country: "EC" },
    
    { name: "La Paz", country: "BO" },
    { name: "Santa Cruz de la Sierra", country: "BO" },
    { name: "Cochabamba", country: "BO" },
    { name: "Sucre", country: "BO" },
    
    { name: "Asunción", country: "PY" },
    { name: "Ciudad del Este", country: "PY" },
    { name: "San Lorenzo", country: "PY" },
    
    { name: "Montevideo", country: "UY" },
    { name: "Salto", country: "UY" },
    { name: "Paysandú", country: "UY" },
    
    // Africa
    { name: "Cairo", country: "EG" },
    { name: "Alexandria", country: "EG" },
    { name: "Giza", country: "EG" },
    { name: "Shubra El-Kheima", country: "EG" },
    { name: "Port Said", country: "EG" },
    { name: "Suez", country: "EG" },
    { name: "Luxor", country: "EG" },
    { name: "Aswan", country: "EG" },
    
    { name: "Lagos", country: "NG" },
    { name: "Kano", country: "NG" },
    { name: "Ibadan", country: "NG" },
    { name: "Abuja", country: "NG" },
    { name: "Port Harcourt", country: "NG" },
    { name: "Benin City", country: "NG" },
    { name: "Kaduna", country: "NG" },
    { name: "Jos", country: "NG" },
    
    { name: "Johannesburg", country: "ZA" },
    { name: "Cape Town", country: "ZA" },
    { name: "Durban", country: "ZA" },
    { name: "Pretoria", country: "ZA" },
    { name: "Port Elizabeth", country: "ZA" },
    { name: "Bloemfontein", country: "ZA" },
    { name: "East London", country: "ZA" },
    { name: "Pietermaritzburg", country: "ZA" },
    
    { name: "Nairobi", country: "KE" },
    { name: "Mombasa", country: "KE" },
    { name: "Kisumu", country: "KE" },
    { name: "Nakuru", country: "KE" },
    { name: "Eldoret", country: "KE" },
    
    { name: "Dar es Salaam", country: "TZ" },
    { name: "Mwanza", country: "TZ" },
    { name: "Arusha", country: "TZ" },
    { name: "Dodoma", country: "TZ" },
    { name: "Mbeya", country: "TZ" },
    
    { name: "Kampala", country: "UG" },
    { name: "Gulu", country: "UG" },
    { name: "Lira", country: "UG" },
    { name: "Mbarara", country: "UG" },
    
    { name: "Addis Ababa", country: "ET" },
    { name: "Dire Dawa", country: "ET" },
    { name: "Mek'ele", country: "ET" },
    { name: "Gondar", country: "ET" },
    
    { name: "Khartoum", country: "SD" },
    { name: "Omdurman", country: "SD" },
    { name: "Port Sudan", country: "SD" },
    
    { name: "Casablanca", country: "MA" },
    { name: "Rabat", country: "MA" },
    { name: "Fez", country: "MA" },
    { name: "Marrakesh", country: "MA" },
    { name: "Tangier", country: "MA" },
    { name: "Agadir", country: "MA" },
    { name: "Meknes", country: "MA" },
    
    { name: "Algiers", country: "DZ" },
    { name: "Oran", country: "DZ" },
    { name: "Constantine", country: "DZ" },
    { name: "Annaba", country: "DZ" },
    { name: "Blida", country: "DZ" },
    
    { name: "Tunis", country: "TN" },
    { name: "Sfax", country: "TN" },
    { name: "Sousse", country: "TN" },
    { name: "Kairouan", country: "TN" },
    
    { name: "Tripoli", country: "LY" },
    { name: "Benghazi", country: "LY" },
    { name: "Misrata", country: "LY" },
    
    { name: "Accra", country: "GH" },
    { name: "Kumasi", country: "GH" },
    { name: "Tamale", country: "GH" },
    { name: "Takoradi", country: "GH" },
    
    { name: "Dakar", country: "SN" },
    { name: "Touba", country: "SN" },
    { name: "Thiès", country: "SN" },
    
    { name: "Luanda", country: "AO" },
    { name: "Huambo", country: "AO" },
    { name: "Lobito", country: "AO" },
    
    { name: "Harare", country: "ZW" },
    { name: "Bulawayo", country: "ZW" },
    { name: "Chitungwiza", country: "ZW" },
    
    { name: "Lusaka", country: "ZM" },
    { name: "Kitwe", country: "ZM" },
    { name: "Ndola", country: "ZM" },
    
    { name: "Maputo", country: "MZ" },
    { name: "Matola", country: "MZ" },
    { name: "Beira", country: "MZ" },
    
    // Oceania
    { name: "Sydney", country: "AU" },
    { name: "Melbourne", country: "AU" },
    { name: "Brisbane", country: "AU" },
    { name: "Perth", country: "AU" },
    { name: "Adelaide", country: "AU" },
    { name: "Gold Coast", country: "AU" },
    { name: "Newcastle", country: "AU" },
    { name: "Canberra", country: "AU" },
    { name: "Sunshine Coast", country: "AU" },
    { name: "Wollongong", country: "AU" },
    { name: "Hobart", country: "AU" },
    { name: "Geelong", country: "AU" },
    { name: "Townsville", country: "AU" },
    { name: "Cairns", country: "AU" },
    { name: "Darwin", country: "AU" },
    
    { name: "Auckland", country: "NZ" },
    { name: "Wellington", country: "NZ" },
    { name: "Christchurch", country: "NZ" },
    { name: "Hamilton", country: "NZ" },
    { name: "Tauranga", country: "NZ" },
    { name: "Napier-Hastings", country: "NZ" },
    { name: "Dunedin", country: "NZ" },
    { name: "Palmerston North", country: "NZ" },
    { name: "Nelson", country: "NZ" },
    { name: "Rotorua", country: "NZ" },
    
    { name: "Port Moresby", country: "PG" },
    { name: "Lae", country: "PG" },
    { name: "Arawa", country: "PG" },
    
    { name: "Suva", country: "FJ" },
    { name: "Nadi", country: "FJ" },
    { name: "Lautoka", country: "FJ" }
];
console.log('✅ Cities loaded:', POPULAR_CITIES.length, 'cities available');
